apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylab1-cafe-app
  labels:
    app: cafe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-app
  template:
    metadata:
      labels:
        app: cafe-app
    spec:
      containers:
      - name: cafe-app
        image: omarabdelwahab1/cafe-app
        ports:
        - containerPort: 80
  strategy:  # Corrected spelling from "strattegy" to "strategy"
    type: RollingUpdate
    rollingUpdate:  # Corrected spelling from "rollingupdate" to "rollingUpdate"
      maxSurge: 1
      maxUnavailable: 1

